name: deploy to lambda
on: [push]
jobs:

  deploy_source:
    name: deploy lambda from source
    runs-on: ubuntu-latest
    steps:
      - name: checkout source code
        uses: actions/checkout@v1
      - name: default deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: HelloWorld
          source: lambda_function.py, airtable_api.py, buffer_output.py, circular_queue.py, __init__.py, constants.py, libraries, urllib3,
                  urllib3-1.26.6.dist-info, requests, requests-2.26.0.dist-info, idna, idna-3.2.dist-info, charset_normalizer,
                  charset_normalizer-2.0.4.dist-info, certifi, certifi-2021.5.30.dist-info, bin

